apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: trading
    user: trading_user
    secureJsonData:
      password: change_me
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false

  - name: Redis
    type: redis-datasource
    url: redis://redis:6379
    isDefault: false
    editable: false
